<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Model_user extends CI_Model {

	private $tb1 = 'DEMAGE_DETAILS';
	private $tb2 = 'TYPE_DEMAGE';
	private $tb3 = 'USERS';
	private $tb4 = 'TICKET_DETAILS';

	public function get_listticket(){
    	$result = $this->db->query('SELECT * FROM TICKET ORDER BY ID_TICKET DESC');
    	return $result;
  	}

  	public function get_joindata()
  	{
  		$result = $this->db->query("SELECT TICKET.ID_TICKET, TICKET.ID_TICKET_DETAILS, TICKET.TOKEN, TICKET.STATUS, TICKET_DETAILS.ID_TYPE_DEMAGES, TICKET_DETAILS.ID_USERS, TICKET_DETAILS.SUBJECT, TICKET_DETAILS.DESCRIPTION, TYPE_DEMAGE.TYPE_DEMAGE, TYPE_DEMAGE.ID_DEMAGE_DETAILS, TYPE_DEMAGE.ID_USERS, DEMAGE_DETAILS.DEMAGE_DETAILS, USERS.NAME, USERS.DIVISION FROM TICKET JOIN TICKET_DETAILS ON TICKET.ID_TICKET_DETAILS = TICKET_DETAILS.ID_TICKET_DETAILS JOIN TYPE_DEMAGE ON TICKET_DETAILS.ID_TYPE_DEMAGES = TYPE_DEMAGE.ID_TYPE_DEMAGES JOIN DEMAGE_DETAILS ON TYPE_DEMAGE.ID_DEMAGE_DETAILS = DEMAGE_DETAILS.ID_DEMAGE_DETAILS JOIN USERS ON TICKET_DETAILS.ID_USERS = USERS.ID_USERS");
    	return $result;
  	}

//     SELECT TICKET.ID_TICKET_DETAILS, TICKET.TOKEN, TICKET.STATUS, TICKET_DETAILS.ID_TYPE_DEMAGES, TICKET_DETAILS.ID_USERS, TICKET_DETAILS.SUBJECT,
// TICKET_DETAILS.DESCRIPTION, TYPE_DEMAGE.TYPE_DEMAGE, TYPE_DEMAGE.ID_DEMAGE_DETAILS, TYPE_DEMAGE.ID_USERS, DEMAGE_DETAILS.DEMAGE_DETAILS
// FROM TICKET 
// JOIN TICKET_DETAILS ON TICKET.ID_TICKET_DETAILS = TICKET_DETAILS.ID_TICKET_DETAILS
// JOIN TYPE_DEMAGE ON TICKET_DETAILS.ID_TYPE_DEMAGES = TYPE_DEMAGE.ID_TYPE_DEMAGES
// JOIN DEMAGE_DETAILS ON TYPE_DEMAGE.ID_DEMAGE_DETAILS = DEMAGE_DETAILS.ID_DEMAGE_DETAILS

}

/* End of file model_user.php */
/* Location: ./application/models/admin/model_user.php */