<?php
defined('BASEPATH') OR exit('No direct script access allowed');
/**
 * 
 */
class Model_Pic_admin extends CI_Model
{

  protected $software = 'software';
  protected $hardware = 'hardware';

	public function get_dataPIC(){
    	$result = $this->db->query('SELECT * FROM PIC');
    	return $result;
  	}

  	public function get_allticket()
  	{
  		$result = $this->db->query("SELECT * FROM TICKET JOIN TICKET_DETAILS ON TICKET.ID_TICKET_DETAILS=TICKET_DETAILS.ID_TICKET_DETAILS JOIN TYPE_DEMAGE ON TICKET_DETAILS.ID_TYPE_DEMAGES = TYPE_DEMAGE.ID_TYPE_DEMAGES JOIN DEMAGE_DETAILS ON TYPE_DEMAGE.ID_DEMAGE_DETAILS=DEMAGE_DETAILS.ID_DEMAGE_DETAILS JOIN USERS ON TICKET_DETAILS.ID_USERS = USERS.ID_USERS ORDER BY DEMAGE_DETAILS.RANK ASC");
      	return $result;
  	}

    public function get_alltickethardware()
    {
      $result = $this->db->query("SELECT * FROM TICKET JOIN TICKET_DETAILS ON TICKET.ID_TICKET_DETAILS=TICKET_DETAILS.ID_TICKET_DETAILS JOIN TYPE_DEMAGE ON TICKET_DETAILS.ID_TYPE_DEMAGES = TYPE_DEMAGE.ID_TYPE_DEMAGES JOIN DEMAGE_DETAILS ON TYPE_DEMAGE.ID_DEMAGE_DETAILS=DEMAGE_DETAILS.ID_DEMAGE_DETAILS JOIN USERS ON TICKET_DETAILS.ID_USERS = USERS.ID_USERS WHERE USERS.EXPERTISE='$this->hardware' OR TYPE_DEMAGE.TYPE_DEMAGE='hardware' ORDER BY DEMAGE_DETAILS.RANK ASC");
        return $result;
    }

    public function get_allticketsoftware()
    {
      $result = $this->db->query("SELECT * FROM TICKET JOIN TICKET_DETAILS ON TICKET.ID_TICKET_DETAILS=TICKET_DETAILS.ID_TICKET_DETAILS JOIN TYPE_DEMAGE ON TICKET_DETAILS.ID_TYPE_DEMAGES = TYPE_DEMAGE.ID_TYPE_DEMAGES JOIN DEMAGE_DETAILS ON TYPE_DEMAGE.ID_DEMAGE_DETAILS=DEMAGE_DETAILS.ID_DEMAGE_DETAILS JOIN USERS ON TICKET_DETAILS.ID_USERS = USERS.ID_USERS WHERE USERS.EXPERTISE='$this->software' OR TYPE_DEMAGE.TYPE_DEMAGE='software' ORDER BY DEMAGE_DETAILS.RANK ASC");
        return $result;
    }

  	public function get_listticket()
  	{
  		$result = $this->db->query("SELECT * FROM TICKET JOIN TICKET_DETAILS ON TICKET.ID_TICKET_DETAILS=TICKET_DETAILS.ID_TICKET_DETAILS JOIN TYPE_DEMAGE ON TICKET_DETAILS.ID_TYPE_DEMAGES = TYPE_DEMAGE.ID_TYPE_DEMAGES JOIN DEMAGE_DETAILS ON TYPE_DEMAGE.ID_DEMAGE_DETAILS=DEMAGE_DETAILS.ID_DEMAGE_DETAILS JOIN USERS ON TICKET_DETAILS.ID_USERS = USERS.ID_USERS WHERE TICKET.STATUS = '2' ORDER BY DEMAGE_DETAILS.RANK ASC");
      	return $result;
  	}

    public function get_alltickethardwarestatus2()
    {
      $result = $this->db->query("SELECT * FROM TICKET JOIN TICKET_DETAILS ON TICKET.ID_TICKET_DETAILS=TICKET_DETAILS.ID_TICKET_DETAILS JOIN TYPE_DEMAGE ON TICKET_DETAILS.ID_TYPE_DEMAGES = TYPE_DEMAGE.ID_TYPE_DEMAGES JOIN DEMAGE_DETAILS ON TYPE_DEMAGE.ID_DEMAGE_DETAILS=DEMAGE_DETAILS.ID_DEMAGE_DETAILS JOIN USERS ON TICKET_DETAILS.ID_USERS = USERS.ID_USERS WHERE TICKET.STATUS = '2' AND USERS.EXPERTISE='$this->hardware' OR TYPE_DEMAGE.TYPE_DEMAGE='hardware' ORDER BY DEMAGE_DETAILS.RANK ASC");
        return $result;
    }

    public function get_allticketsoftwarestatus2()
    {
      $result = $this->db->query("SELECT * FROM TICKET JOIN TICKET_DETAILS ON TICKET.ID_TICKET_DETAILS=TICKET_DETAILS.ID_TICKET_DETAILS JOIN TYPE_DEMAGE ON TICKET_DETAILS.ID_TYPE_DEMAGES = TYPE_DEMAGE.ID_TYPE_DEMAGES JOIN DEMAGE_DETAILS ON TYPE_DEMAGE.ID_DEMAGE_DETAILS=DEMAGE_DETAILS.ID_DEMAGE_DETAILS JOIN USERS ON TICKET_DETAILS.ID_USERS = USERS.ID_USERS WHERE TICKET.STATUS = '2' AND USERS.EXPERTISE='$this->software' OR TYPE_DEMAGE.TYPE_DEMAGE='software' ORDER BY DEMAGE_DETAILS.RANK ASC");
        return $result;
    }

    public function get_allticketstatus2()
    {
      $result = $this->db->query("SELECT * FROM TICKET JOIN TICKET_DETAILS ON TICKET.ID_TICKET_DETAILS=TICKET_DETAILS.ID_TICKET_DETAILS JOIN TYPE_DEMAGE ON TICKET_DETAILS.ID_TYPE_DEMAGES = TYPE_DEMAGE.ID_TYPE_DEMAGES JOIN DEMAGE_DETAILS ON TYPE_DEMAGE.ID_DEMAGE_DETAILS=DEMAGE_DETAILS.ID_DEMAGE_DETAILS JOIN USERS ON TICKET_DETAILS.ID_USERS = USERS.ID_USERS WHERE TICKET.STATUS = '2' ORDER BY DEMAGE_DETAILS.RANK ASC");
        return $result;
    }

  	public function update_status($ID_TICKET,$status,$update_at){   
        $hasil=$this->db->query("UPDATE TICKET SET STATUS='$status',UPDATED_AT='$update_at' WHERE ID_TICKET='$ID_TICKET'");
        return $hasil;
    }
	
}